### ISSUE TITLE
no js file generated on folder split

### ISSUE THREAD

**Issue by sluxzer** [zhorton34/laravel-mix-code-splitter#1]
Hey there.

After installing this extension. i need manually create split folter on resource/js & public/js path 

Then after run npm run prod I don't see any file being created on resource/js/split or public/js/split 

although on my bundler i see all the js is separated.

Thank you.

**Comment by zhorton34** [comment]
Sounds like that's some webpack magic, it's "bundling" it to make more efficient. Same concept applies though.

Is it properly loading the files on your production @sluxzer?

**Comment by zhorton34** [comment]
Closing this issue for the time being due to no response with further details.
